# Generated by Django 3.0.9 on 2020-08-18 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200818_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='employees',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Employees'),
        ),
    ]
