# Generated by Django 3.0.9 on 2020-08-18 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0004_auto_20200818_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee',
                     'verbose_name_plural': 'Employees'},
        ),
    ]
